from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

OUT='Rock_Supply_Intelligence_Canonical_Data_Contract_v0_1.docx'
BLUE='17365D'; PALE='F5F8FB'; BORDER='D9D9D9'
def shade(c,color):
    e=OxmlElement('w:shd'); e.set(qn('w:fill'),color); c._tc.get_or_add_tcPr().append(e)
def cell(c,s,b=False,w=False):
    c.text=''; p=c.paragraphs[0]; p.paragraph_format.space_after=Pt(0); r=p.add_run(str(s)); r.bold=b; r.font.size=Pt(8.5); r.font.color.rgb=RGBColor(255,255,255) if w else RGBColor(0,0,0); c.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
    tc=c._tc.get_or_add_tcPr(); m=OxmlElement('w:tcMar')
    for x in ('top','start','bottom','end'):
        z=OxmlElement('w:'+x); z.set(qn('w:w'),'100'); z.set(qn('w:type'),'dxa'); m.append(z)
    tc.append(m); bd=OxmlElement('w:tcBorders')
    for x in ('top','left','bottom','right'):
        z=OxmlElement('w:'+x); z.set(qn('w:val'),'single'); z.set(qn('w:sz'),'4'); z.set(qn('w:color'),BORDER); bd.append(z)
    tc.append(bd)
def tbl(d,heads,rows):
    t=d.add_table(rows=1,cols=len(heads)); t.alignment=WD_TABLE_ALIGNMENT.CENTER; t.style='Table Grid'
    for i,x in enumerate(heads): shade(t.rows[0].cells[i],BLUE); cell(t.rows[0].cells[i],x,True,True)
    for n,row in enumerate(rows):
        cs=t.add_row().cells
        for i,x in enumerate(row):
            if n%2: shade(cs[i],PALE)
            cell(cs[i],x)
    d.add_paragraph().paragraph_format.space_after=Pt(1)
def para(d,text,style=None):
    p=d.add_paragraph(style=style); p.paragraph_format.space_after=Pt(6); p.add_run(text); return p
def bullets(d,items):
    for x in items: para(d,x,'List Bullet')
def h(d,x,n=1): d.add_heading(x,n)
def br(d): d.add_page_break()

d=Document(); s=d.sections[0]; s.top_margin=Inches(.68); s.bottom_margin=Inches(.68); s.left_margin=Inches(.7); s.right_margin=Inches(.7)
d.styles['Normal'].font.name='Aptos'; d.styles['Normal'].font.size=Pt(10.2)
for x,z in [('Title',22),('Heading 1',15),('Heading 2',12),('Heading 3',10.5)]: d.styles[x].font.name='Aptos Display'; d.styles[x].font.size=Pt(z); d.styles[x].font.color.rgb=RGBColor(0,0,0)
t=d.add_paragraph(style='Title'); t.add_run('Rock Supply Intelligence Canonical Data Contract v0 1')
title_borders=OxmlElement('w:pBdr'); title_bottom=OxmlElement('w:bottom'); title_bottom.set(qn('w:val'),'nil'); title_borders.append(title_bottom); t._p.get_or_add_pPr().append(title_borders)
p=para(d,'Sunlighten oriented shadow POC  •  Internal working specification  •  7 September 2026'); p.runs[0].italic=True
para(d,'Purpose. This contract defines the records, evidence, controls, and test fixtures for a supply intelligence proof of concept. It makes external signals traceable to business exposure without permitting the system to invent facts or act on operations. The design is local-model-first, provider-agnostic, cloud-optional, and human-in-the-loop.')
h(d,'Decision and operating principles')
tbl(d,['Principle','Contract requirement'],[
['Facts before advice','An exposure or recommendation is never a source fact. Each material conclusion links to evidence and deterministic calculation inputs.'],
['Local-model-first','A local model may classify, extract, summarize, or propose structured candidates. It is not required for deterministic joins, time math, geospatial tests, financial calculation, or authorization.'],
['Provider-agnostic','Connectors map provider payloads to these schemas; provider-specific fields remain in preserved raw payloads, never in canonical business logic.'],
['Cloud-optional','The POC functions with local storage, local inference, and scheduled pulls. Cloud services may be adapters, not trust anchors.'],
['Human control','No recommendation changes a booking, inventory allocation, carrier instruction, or customer commitment. Approval is explicit and recorded.']])
h(d,'Scope and identifiers')
para(d,'All canonical records are JSON-compatible objects. UUIDv7 is preferred for generated identifiers; upstream identifiers are retained as external_ids. Times are RFC 3339 UTC. Money is ISO 4217 currency plus decimal amount. Coordinates use WGS 84 longitude then latitude. An implementation may serialize dates as ISO 8601 strings but must preserve source precision.')
tbl(d,['Shared field','Required','Meaning'],[['id','Yes','Stable canonical record identifier; never silently reused.'],['schema_version','Yes','Contract version, initially 0.1.'],['tenant_id','Yes in multi-tenant deployments','Logical business boundary; use sunlighten-shadow in the POC.'],['status','Yes','Lifecycle: active, superseded, retracted, archived, or draft where applicable.'],['created_at / updated_at','Yes','System timestamps, UTC.'],['external_ids','Optional','Array of {system, value, url?}; preserves source/business identifiers.'],['evidence_ids','Required for externally derived or material records','References to Evidence records; empty only for manually entered business facts with actor audit.']])

br(d); h(d,'Common semantics and controls')
h(d,'Confidence',2); para(d,'Confidence supports triage; it does not turn an assertion into a fact. Store confidence from 0.00 to 1.00, its method, and its scope. It is required for AI-extracted claims, inferred event impact, and recommendations. It is optional for direct authoritative facts; 1.00 means successful capture of the stated source record, never real-world certainty.')
tbl(d,['Band','Range','Meaning and control'],[['Verified','0.90–1.00','Direct authoritative source or human verification. Retain source and capture time.'],['Strong','0.75–0.89','Corroborated sources or high-quality extraction. May create exposure if deterministic linkage exists.'],['Provisional','0.50–0.74','Analyst review and monitoring only; cannot alone support a material recommendation.'],['Weak','0.01–0.49','Lead only. Do not publish as an operational claim.'],['Unknown','null','No defensible estimate; route for review or omit the inference.']])
h(d,'Materiality and evidence',2)
bullets(d,['A material claim is any statement of disruption, delay, financial exposure, customer impact, legal or compliance risk, or recommended action.','Every material claim cites Evidence IDs, identifies whether it is observed, extracted, inferred, or calculated, and states its confidence method.','Evidence preserves capture metadata, content hash where permitted, source locator, publication time when known, and an excerpt or structured payload path sufficient to reproduce the claim.','Retraction or correction creates a new record and links supersedes or retracts relationships; it never overwrites history.'])
h(d,'Deterministic versus AI boundary',2)
tbl(d,['Deterministic service owns','AI may assist with','AI may not do'],[['Schema validation; ID matching; unit/time conversion; geospatial tests; shipment joins; ETA/inventory arithmetic; severity thresholds; policy gates; audit writes.','Classification; entity/location/event extraction; translation; evidence summaries; candidate normalization; analyst-facing explanation; nonbinding recommendation drafts.','Create or modify business facts; assert unsupported causality; choose an unverified entity match; execute an operational action; bypass evidence, confidence, or approval gates.']])

br(d); h(d,'Canonical schemas')
para(d,'Notation: R required, O optional, C conditionally required. Evidence means one or more linked Evidence IDs unless stated otherwise. Enumerations are closed unless an explicit other value is supplied with a normalized label.')
h(d,'ExternalEvent',2)
tbl(d,['Field','Req','Type or allowed values','Notes'],[['id, schema_version, status, timestamps','R','shared fields','See common fields.'],['event_type','R','weather, port_disruption, vessel_anomaly, earthquake, labor, geopolitical, infrastructure, carrier_exception, customs_regulatory, wildfire, aviation_disruption, road_disruption, other','Use most specific supported class.'],['event_state','R','reported, confirmed, ongoing, resolved, cancelled, unknown','Real-world state, not record lifecycle.'],['title','R','string','Neutral, source-grounded label.'],['start_time, end_time','C','RFC 3339 UTC','Start when known; end when known/resolved.'],['geometry','C','Point, LineString, Polygon, bbox','Required when location is actionable; include precision_m.'],['locations, entities','O','arrays of canonical refs','Port, airport, carrier, facility, route.'],['severity','R','none, low, moderate, high, severe, unknown','Normalize by versioned source rules; retain source_severity.'],['source_event_ids','O','array','Provider identifiers.'],['observed_or_inferred','R','observed, extracted, inferred, calculated','Observed only for direct feed facts.'],['confidence, evidence_ids','R','number; array','At least one Evidence ID.']])
h(d,'Evidence',2)
tbl(d,['Field','Req','Type or allowed values','Notes'],[['id, schema_version, status, timestamps','R','shared fields','Append-only except lifecycle links.'],['source_name, source_type','R','string; authoritative_feed, government, open_data, news, satellite, community, internal, analyst','Do not label a source authoritative without basis.'],['source_url or source_locator','R','URI or provider path','Resolvable when access permits.'],['retrieved_at','R','UTC timestamp','Connector capture time.'],['published_at, observed_at','O','UTC timestamps','Preserve separately; unknown is null.'],['content_hash','R where content retained','SHA-256 string','Hash normalized bytes and record hash method.'],['raw_ref','R','immutable object/path reference','Original payload or permitted snapshot.'],['excerpt_or_payload_path','R','string / JSONPath','Minimum auditable support.'],['license, access_constraints','O','strings','Reuse and retention handling.'],['extraction','R','method: deterministic|local_ai|cloud_ai|human; model_or_rule; prompt_version?; reviewer?','AI needs model and prompt/template version.']])

br(d); h(d,'Business and logistics schemas')
h(d,'PurchaseOrder',2)
tbl(d,['Field','Req','Type or allowed values','Notes'],[['po_number','R','string','Business key; unique per legal entity.'],['supplier_id, order_date, status','R','ref, date, draft|open|partially_received|received|cancelled|closed','ERP or synthetic fixture snapshot.'],['currency, lines','R','ISO 4217; array','Line: sku_id, quantity_ordered, unit_cost?, promised_date?, received_quantity?.'],['ship_to_location_id, incoterm','O','refs/string','Retain source terminology.'],['evidence_ids','C','array','Required for imported/external data; internal audit may substitute actor/change record.']])
h(d,'Shipment and ShipmentLeg',2)
tbl(d,['Object','Required fields','Optional fields and rules'],[['Shipment','shipment_number; status planned|booked|in_transit|arrived|delivered|cancelled|unknown; mode ocean|air|road|rail|parcel|multimodal; origin; destination; planned departure/arrival; legs','carrier_id, booking ref, bill of lading, actual times, owner, incoterm, PO refs, container refs. Actual timestamps need Evidence or internal audit.'],['ShipmentLeg','leg_sequence; mode; origin; destination; planned departure/arrival; status','carrier_id; vessel/flight ref; actual times; route geometry; handoff location; transit baseline; related events. Leg sequence is 1-based and immutable within shipment version.'],['Container','container_number; container_type; status','shipment_id; seal; owner; gross weight; last known position; tracking events. Validate ISO 6346 checksum where format allows; do not manufacture a number.'],['CarrierEvent','event_type; event_time; subject_type; subject_id; source; evidence_ids','location; facility; delay_minutes; status; raw_status. Event type: departed, arrived, gated_in, gated_out, loaded, discharged, customs_hold, exception, eta_changed, cancelled, other.']])
h(d,'InventoryPosition and SalesOrder',2)
tbl(d,['Object','Required fields','Optional fields and rules'],[['InventoryPosition','snapshot_at; sku_id; location_id; on_hand; allocated; available','on_order; in_transit; safety_stock; reorder_point; unit. available = on_hand − allocated unless documented ERP semantic differs.'],['SalesOrder','sales_order_number; status; order_date; requested_ship_date; lines','customer_id; promised_ship_date; priority; ship_to location; currency. Lines: sku_id, ordered, allocated, shipped. Customer identity may be pseudonymized.']])

br(d); h(d,'Master data and decision schemas')
h(d,'SKU and Supplier',2)
tbl(d,['Object','Required fields','Optional fields and rules'],[['SKU','sku_code; description; base_unit; active','product_family; lead_time_days; safety_stock; criticality low|medium|high|critical; substitute_sku_ids; country of origin; dimensions/weight. Lead-time changes are time-versioned.'],['Supplier','supplier_code; legal_name; status active|inactive|on_hold|unknown','addresses; facilities; country; supplier_risk_tier; contact refs; external IDs. Screening results are external events/evidence, not a mutable supplier label.']])
h(d,'Exposure',2)
tbl(d,['Field','Req','Type or allowed values','Notes'],[['id, event_id, exposure_type, status','R','delay, capacity_loss, inventory_stockout, customer_commitment, financial, compliance, route_disruption; candidate|reviewed|confirmed|dismissed|resolved','Exposure is a conclusion, not a source fact.'],['subject_type, subject_id','R','shipment|shipment_leg|container|PO|SKU|sales_order|supplier|location; canonical ID','One exposure per directly affected subject.'],['linkage_method','R','deterministic_geospatial, deterministic_entity, deterministic_time_window, rule_based, analyst_confirmed','AI alone is prohibited.'],['impact_window','R','start/end UTC','Estimated allowed only with method.'],['expected_delay','O','min_hours, max_hours, method','Null when unsupported.'],['affected_sku_ids, sales_order_ids','O','arrays','Derived through deterministic joins.'],['inventory_risk','O','none|watch|at_risk|stockout_expected','Cite snapshot/time calculation.'],['financial_exposure','O','amount, currency, method, assumptions','No false precision; unknown is null.'],['confidence, evidence_ids, calculation_trace','R','number; array; array','Trace input IDs, rules/version, computed outputs.']])
h(d,'Recommendation',2)
tbl(d,['Field','Req','Type or allowed values','Notes'],[['id, exposure_ids, action_type, status','R','monitor, verify, contact_carrier, expedite_review, allocate_review, alternate_route_review, customer_commitment_review, compliance_review, no_action; draft|pending_approval|approved|rejected|executed|withdrawn','Action names deliberately include review, not action.'],['rationale, assumptions','R','strings/arrays','Separate source facts, inference, recommendation.'],['priority, confidence, evidence_ids','R','low|medium|high|urgent; number; array','Confidence is suitability, not success probability.'],['human_approval','R','state not_requested|pending|approved|rejected; actor?; at?; notes?','Only a human can move to approved.'],['execution_record','C','actor, time, external ref','Required only if an approved human later executes an action.'],['model_trace','C','model/provider/prompt/version','Required if AI contributed; local versus cloud explicit.']])

br(d); h(d,'Normalization and source mapping')
h(d,'Normalization rules',2)
bullets(d,['Do not replace source values. Store raw_value, normalized_value, unit, and transformation_rule whenever conversion could affect meaning.','Geography resolves deterministically: authoritative code/coordinate, then UN LOCODE, then trusted port/airport registry, then GeoNames/OpenStreetMap. Ambiguous matches remain unresolved for review.','Port, airport, facility, vessel, flight, and carrier references are typed identifiers. A plain name is not an identity match.','Severity maps source scale to canonical enum with a versioned mapping table. Unknown source scales map to unknown, not high.','Events deduplicate only when connector/provider ID matches or a versioned rule establishes same type, proximate time, compatible geometry/entity. Preserve all evidence and conflicts.','Business data is a timestamped snapshot. Exposure math declares its snapshot and planning times.'])
h(d,'Source mapping guidance',2)
tbl(d,['Source','Primary output','Key mapping and guardrail'],[['Taiwan CWA','ExternalEvent weather/earthquake; Evidence','Map warning/product ID, issue/effective/expiry, forecast geometry, alert class, typhoon name. Do not infer port closure from weather alert alone.'],['Taiwan port and open data','ExternalEvent port_disruption; CarrierEvent; Evidence','Map port code, berth/terminal if explicit, notice state/effective time. Preserve Chinese source and translation provenance.'],['AISStream','CarrierEvent vessel position; ExternalEvent vessel_anomaly; Evidence','AIS is observational and incomplete. Validate MMSI/IMO. Anomaly needs deterministic rule and trace; absence of pings is not delay.'],['GDELT and ReliefWeb','ExternalEvent candidate; Evidence','Discovery/news only. AI extraction is permitted; material claims need corroboration or analyst review.'],['GDACS and USGS','ExternalEvent earthquake/wildfire/hazard; Evidence','Map event ID, magnitude, depth, geometry, event time, alert level. Proximity is deterministic; operational impact is not assumed.'],['NWS NOAA and NOAA CO OPS','ExternalEvent weather/coastal hazard; Evidence','Map product/VTEC, station, forecast zone, water level, datum/unit. Conversions are versioned.'],['USCG NAVCEN','ExternalEvent navigation/GPS/maritime safety; Evidence','Map notice ID, region, effective interval, advisory. It is not a shipment-status feed.'],['NASA FIRMS','ExternalEvent wildfire; Evidence','Map observation time, confidence class, FRP, coordinate, source. Detection is not closure.'],['FAA NAS status','ExternalEvent aviation_disruption; Evidence','Map airport/facility, program, delay or ground-stop scope, valid time. Link only via airport/time match.'],['511 Caltrans','ExternalEvent road_disruption; Evidence','Use only applicable North American drayage/last-mile segments. Map roadway, direction, closure, geometry/time.'],['MarineCadastre','Reference geometry; Evidence','Reference context only; version dataset and license.'],['Trade.gov CSL and OFAC','ExternalEvent compliance/screening; Evidence','Use exact screened party and list/version/date. Possible name match is review cue, never legal finding.'],['UN LOCODE','Reference place identifier; Evidence','Preferred trade-location normalizer. Retain subdivision/function/status/version.'],['GeoNames and OpenStreetMap','Reference place geometry/name; Evidence','Fallback geocoding only. Record version, query, selected candidate, ambiguity rationale.']])

br(d); h(d,'Audit provenance and human workflow')
h(d,'Minimum audit trail',2)
tbl(d,['When','Must record'],[['Ingestion','Connector/version, source request identity without secrets, retrieval time, raw reference/hash, parser version, license/access constraints, source-to-canonical mapping outcome.'],['Normalization','Original and normalized value, transformation rule/version, resolver candidates for ambiguity, and human override.'],['AI contribution','Model family/version, local/cloud execution class, prompt/template version, input Evidence IDs, structured output, validation/retry, reviewer decision.'],['Calculation','Rule/version, input IDs and snapshot times, arithmetic outputs, thresholds, geospatial/time method, result.'],['Human decision','Reviewer identity, timestamp, approval/rejection/override reason, action scope, downstream execution reference if action occurs.']])
h(d,'Human in the loop state flow',2); para(d,'External signal → candidate event → validated event → deterministic exposure candidate → analyst review → recommendation draft → human approval or rejection → separately recorded operational execution. Every transition is attributable; a rejected or withdrawn recommendation remains visible in history.')
h(d,'Security and data handling',2); bullets(d,['Keep API keys, customer PII, carrier credentials, and raw commercial data outside canonical payloads; reference protected vault/object locations.','Apply source licenses, rate limits, retention rules, and access controls at connector and evidence layers. Open data does not imply unrestricted redistribution.','Pseudonymize customers and use synthetic business fixtures for the shadow POC unless an approved data-use path exists.'])

br(d); h(d,'Benchmark fixtures and acceptance invariants')
h(d,'Fixture design',2); para(d,'Each fixture is a versioned, replayable package containing raw source snapshots or lawful redacted equivalents, expected normalized records, synthetic business snapshots, expected deterministic linkages, and an adjudication note. Fixtures run offline after capture so provider availability does not change results.')
tbl(d,['Fixture component','Requirement'],[['Manifest','Fixture ID, scenario title, capture date, source licenses, schema/rule/model versions, expected outcome status, owner.'],['Raw evidence','Immutable payloads/excerpts with hashes, retrieval metadata, provider IDs. Include positive and distractor items.'],['Business graph','Synthetic POs, shipments/legs, containers, inventory, sales orders, SKUs, suppliers, locations, and snapshot times.'],['Gold labels','Expected events, evidence links, normalized fields, exposure linkage method, calculation trace, recommendation eligibility, explicit non-events.'],['Adjudication','Why gold label is correct; citations; tolerance bands; known ambiguity; reviewer approvals.']])
h(d,'Required benchmark scenarios',2)
bullets(d,['Taiwan typhoon warning near, but not equal to, a port closure: separate weather observation from port-operational claim.','Earthquake near a transit route with no affected shipment: avoid false exposure.','AIS position gap for known vessel: at most monitored anomaly, never a delay claim.','Authoritative FAA or 511 disruption linked to a time-matched air/road leg: calculate linkage and preserve evidence.','News-only geopolitical report with ambiguous location/entity: candidate pending corroboration or human review.','Inventory snapshot showing deterministic stockout risk after accepted delay range: show inputs, assumptions, math.','Sanctions-list possible name match: compliance review only; no legal finding.'])
h(d,'Acceptance invariants',2)
tbl(d,['Invariant','Acceptance test'],[['No invented business facts','Every PO, shipment, leg, container, inventory, sales order, SKU, and supplier fact comes from fixture, approved internal source, or clearly flagged synthetic fixture. AI cannot originate these facts.'],['Evidence for material claims','100% of material event, exposure, and recommendation claims reference auditable Evidence IDs. Test fails if cited evidence is removed and assertion becomes unsupported.'],['No autonomous operational action','Zero writes/API calls to ERP, TMS, carrier, booking, inventory allocation, customer commitment, or compliance disposition systems from detection/recommendation workflows. Execution requires separately recorded human approval.'],['Schema integrity','At least 99% valid canonical records first pass; 99.9% after deterministic repair/retry. Invalid records quarantine with errors, never silent coercion.'],['AI containment','100% AI fields identify model/execution class and pass schema validation. AI-only entity matches cannot create confirmed exposure.'],['Reproducibility','Pinned connector/parser/rule/model versions replay same canonical records and deterministic calculations, apart from permitted nondeterministic text summaries.'],['Traceability','100% confirmed exposures carry linkage method, calculation trace, snapshot timestamps, confidence, and evidence.']])
h(d,'POC exit gate',2); para(d,'Advance only when the invariant suite passes, outcomes are reviewed by a business owner, local-model performance meets separately approved extraction gates, and one end-to-end scenario replays from raw evidence to human-approved recommendation without an operational system write.')
h(d,'Implementation note'); para(d,'This v0.1 contract favors explicitness over coverage. New providers and objects enter through versioned adapters and migration rules, with backward-compatible reading for archived fixtures. Any expansion adding autonomous action, a material risk domain, or customer data requires a fresh control review.')
for sec in d.sections:
    f=sec.footer.paragraphs[0]; f.alignment=WD_ALIGN_PARAGRAPH.CENTER; r=f.add_run('Rock Supply Intelligence  •  Canonical Data Contract v0.1  •  Internal working specification'); r.font.size=Pt(8); r.font.color.rgb=RGBColor(90,90,90)
d.save(OUT); print(OUT)
